# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

env:
  DOCKER_REGISTRY: "docker.elastic.co"
  VAULT_PATH: "kv/ci-shared/observability-ingest/cloud/gcp"
  ASDF_MAGE_VERSION: 1.14.0
  ASDF_GOLANG_VERSION: 1.22.6
  ASDF_TERRAFORM_VERSION: 1.9.2

steps:
  - label: "Integration tests: packaging"
    key: "package-it"
    command: ".buildkite/scripts/steps/integration-package.sh"
    artifact_paths:
      - build/distributions/**
    agents:
      provider: "gcp"
      machineType: "n1-standard-8"

  - label: "Integration tests: upload"
    key: "upload-it"
    depends_on:
      - package-it
    command: ".buildkite/scripts/steps/integration_upload.sh"
    artifact_paths:
      - steps.yml
    agents:
      provider: "gcp"
      machineType: "n1-standard-8"
